[window]

opacity = 0.9

decorations = "Full"
decorations_theme_variant = "Light" # "Dark"

[font]

normal.family = "Hack Nerd Font"
bold.family = "Hack Nerd Font"
italic.family = "Hack Nerd Font"
bold_italic.family = "Hack Nerd Font"

size = 12.0

# github Alacritty Colors

# Default colors
[colors.primary]
background = '#000000'
foreground = '#d3c0a7'

# Normal colors
[colors.normal]
black   = '#072626'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#d3c0a7'

[[colors.indexed_colors]]
index = 16
color = '#d18616'

[[colors.indexed_colors]]
index = 17
color = '#cb2431'

[env]
TERM = "xterm-256color"
